
spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oae9mxu8mcBkk2Y90h7
            client-secret: fVzP7a_DIph9H_Tnt1Pb38EeeGF94Xcnc5gizwFY
        provider:
          okta: 
           authorization-uri: https://dev-265771.oktapreview.com/oauth2/default/v1/authorize
           token-uri: https://dev-265771.oktapreview.com/oauth2/default/v1/token
           user-info-uri: https://dev-265771.oktapreview.com/oauth2/default/v1/userinfo
           jwk-set-uri: https://dev-265771.oktapreview.com/oauth2/default/v1/keys